"""Core SPA pages must fall back to labeled demo rows when live lists are empty."""

from __future__ import annotations

from pathlib import Path

FE = Path(__file__).resolve().parents[2] / "frontend" / "src"


def test_demo_catalog_exports_core_lists() -> None:
    text = (FE / "lib" / "demoCatalog.ts").read_text(encoding="utf-8")
    for token in (
        "DEMO_STOCKS",
        "DEMO_SECTORS",
        "DEMO_PORTFOLIO",
        "DEMO_SELECTOR",
        "DEMO_PANORAMA_ROWS",
        "DEMO_GLOBAL_RADAR",
        "DEMO_LONGHU",
        "DEMO_TDX_BLOCKS",
        "DEMO_FACTORS",
        "DEMO_YANBAO",
        "DEMO_SIGNAL_FLAGS",
        "DEMO_WIZARD_TEMPLATES",
        "DEMO_STRATEGY_SNAPSHOTS",
        "DEMO_MLFLOW_RUNS",
        "DEMO_OBSERVATIONS",
        "DEMO_ALERTS",
        "DEMO_ZEN",
        "DEMO_SELECTION_RESULT",
        "DEMO_PORTFOLIO_DETAIL",
        "DEMO_LISTINGS",
        "DEMO_MANAGED_STOCKS",
        "DEMO_HEDGE_FUND",
        "DEMO_COMMITTEE_SELECTION",
        "DEMO_INVESTMENT_MANAGERS",
        "DEMO_EXPERT_TEAMS",
        "DEMO_MOMENTS",
        "DEMO_MESSAGES",
        "DEMO_WAR_ROOM",
        "DEMO_COMMITTEE_DASHBOARD",
        "DEMO_TASKS",
        "DEMO_SWARM_DASHBOARD",
        "DEMO_SWARM_DESIGNER",
        "DEMO_RESEARCH_PIPELINE",
        "DEMO_RESEARCH_CANVAS",
        "DEMO_AGENTS",
        "DEMO_CAPABILITIES",
        "DEMO_VOICE_BRIEFING",
        "DEMO_ALPHA_FACTORY",
        "DEMO_DECISION_REPLAYS",
        "DEMO_COLLABORATION",
        "DEMO_OBSERVABILITY",
        "DEMO_INVESTMENT_COMMITTEE",
        "DEMO_ARCHITECTURE_ROADMAP",
        "DEMO_RETAIL_ASSISTANT",
        "DEMO_PORTFOLIO_RESONANCE",
        "DEMO_ATTRIBUTION",
        "DEMO_EXPERIMENTS",
        "DEMO_EXPERIMENT_DETAIL",
        "DEMO_FACTOR_DETAIL",
        "DEMO_FACTOR_EVOLUTION",
        "DEMO_INTEGRATION_HUB",
        "DEMO_DECISION_SNAPSHOT",
        "DEMO_DATA_LAKE",
        "DEMO_PROFESSIONAL_WORKBENCH",
        "DEMO_USER_MANAGEMENT",
        "DEMO_USER_SPECTRUM",
        "DEMO_TIER_BOUTIQUE",
        "DEMO_TIER_FUND",
        "DEMO_TIER_INVESTMENT",
        "DEMO_TIER_INSTITUTION",
        "DEMO_SHADOW_ACCOUNT",
        "DEMO_PROFILE",
        "DEMO_TASK_DETAIL",
        "DEMO_QUANT_LAB",
        "DEMO_AI_ANALYSIS",
        "DEMO_AI_CHAT",
        "DEMO_AI_RESEARCH_REPORT",
        "DEMO_BACKTEST",
        "DEMO_LONG_TERM_SELECT",
        "DEMO_NL_STRATEGY",
        "DEMO_OPTIMIZE",
        "DEMO_STOCK_DETAIL",
        "DEMO_STRATEGY_COMPARE",
        "DEMO_ZEN_TERMINAL",
    ):
        assert token in text, token
    assert "600519" in text


def test_core_pages_use_demo_fallback() -> None:
    pages = (
        "SelfStocks.tsx",
        "HotSectors.tsx",
        "Portfolio.tsx",
        "StockSelector.tsx",
        "MarketPanorama.tsx",
        "GlobalRadar.tsx",
        "LonghuBang.tsx",
        "TdxBlocks.tsx",
        "FactorRepository.tsx",
        "YanbaoHub.tsx",
        "SignalFlag.tsx",
        "RunHistory.tsx",
        "StrategyWizard.tsx",
        "StrategySnapshots.tsx",
        "SignalObservations.tsx",
        "AlertCenter.tsx",
        "ZenDashboard.tsx",
        "SelectionResult.tsx",
        "PortfolioDetail.tsx",
        "Marketplace.tsx",
        "StocksManage.tsx",
        "AIHedgeFund.tsx",
        "AICommitteeSelection.tsx",
        "InvestmentManagers.tsx",
        "InvestmentManagerDetail.tsx",
        "ExpertTeams.tsx",
        "Moments.tsx",
        "MessageCenter.tsx",
        "WarRoom.tsx",
        "AICommitteeDashboard.tsx",
        "TaskCenter.tsx",
        "SwarmDashboard.tsx",
        "SwarmDesigner.tsx",
        "ResearchPipeline.tsx",
        "ResearchCanvas.tsx",
        "AgentCenter.tsx",
        "Capabilities.tsx",
        "VoiceBriefing.tsx",
        "AlphaFactory.tsx",
        "DecisionReplaySpace.tsx",
        "CollaborationWorkspace.tsx",
        "Observability.tsx",
        "AIInvestmentCommittee.tsx",
        "ArchitectureRoadmap.tsx",
        "RetailAssistant.tsx",
        "PortfolioResonance.tsx",
        "AttributionDashboard.tsx",
        "ExperimentReport.tsx",
        "FactorDetail.tsx",
        "FactorEvolution.tsx",
        "IntegrationHub.tsx",
        "DecisionSnapshot.tsx",
        "DataLakeHealth.tsx",
        "ProfessionalWorkbench.tsx",
        "UserManagement.tsx",
        "UserSpectrumHub.tsx",
        "UserTiersBoutique.tsx",
        "UserTiersFund.tsx",
        "UserTiersInvestment.tsx",
        "UserTiersInstitution.tsx",
        "ShadowAccount.tsx",
        "Profile.tsx",
        "TaskDetail.tsx",
        "QuantLab.tsx",
        "AIAnalysis.tsx",
        "AIChat.tsx",
        "AIResearchReport.tsx",
        "Backtest.tsx",
        "LongTermSelect.tsx",
        "NLStrategy.tsx",
        "Optimize.tsx",
        "StockDetail.tsx",
        "StrategyCompare.tsx",
        "ZenTerminal.tsx",
    )
    for name in pages:
        text = (FE / "pages" / name).read_text(encoding="utf-8")
        assert "DemoBanner" in text, name
        assert "demoCatalog" in text or "DEMO_" in text, name
        assert "window.location" not in text, name
    managers = (FE / "pages" / "InvestmentManagers.tsx").read_text(encoding="utf-8")
    assert "/app/investment-managers" not in managers
    assert "/investment-managers/" in managers
