from __future__ import annotations
"""Strategy pattern for strategy-as-plugin architecture."""


from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, TypeVar

from app.core.logger import get_logger

logger = get_logger(__name__)

T = TypeVar('T')


@dataclass
class StrategySignal:
    """Signal generated by a strategy."""
    code: str
    direction: str  # long, short
    strength: float  # 0-1
    price: float = 0.0
    target_price: float | None = None
    stop_loss: float | None = None
    confidence: float = 50.0
    reason: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class StrategyResult:
    """Result of strategy execution."""
    signals: list[StrategySignal] = field(default_factory=list)
    metrics: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    elapsed_seconds: float = 0.0
    timestamp: datetime = field(default_factory=datetime.now)


class BaseStrategy(ABC):
    """Base class for all trading strategies."""

    def __init__(self, name: str, params: dict[str, Any] | None = None):
        self.name = name
        self.params = params or {}
        self.enabled = True
        logger.info(f"Strategy '{name}' initialized with params: {self.params}")

    @abstractmethod
    def analyze(self, data: dict[str, Any]) -> StrategyResult:
        """Analyze market data and generate signals."""
        pass

    def validate_params(self) -> bool:
        """Validate strategy parameters."""
        return True

    def reset(self):
        """Reset strategy state."""
        pass


class MACDStrategy(BaseStrategy):
    """MACD crossover strategy."""

    def __init__(self, params: dict | None = None):
        default_params = {
            "fast_period": 12,
            "slow_period": 26,
            "signal_period": 9,
            "threshold": 0.0,
        }
        if params:
            default_params.update(params)
        super().__init__("MACD", default_params)

    def analyze(self, data: dict[str, Any]) -> StrategyResult:
        """Generate signals based on MACD crossover."""
        close = data.get("close", [])
        if len(close) < 30:
            return StrategyResult(errors=["Insufficient data for MACD"])

        signals = []
        fast = self._ema(close, self.params["fast_period"])
        slow = self._ema(close, self.params["slow_period"])
        macd_line = fast - slow
        signal_line = self._ema(macd_line, self.params["signal_period"])

        if len(macd_line) < 2 or len(signal_line) < 2:
            return StrategyResult(errors=["Insufficient data for signal"])

        current_macd = macd_line[-1]
        prev_macd = macd_line[-2]
        current_signal = signal_line[-1]
        prev_signal = signal_line[-2]

        code = data.get("code", "")
        price = data.get("current_price", close[-1] if close else 0)

        if prev_macd <= prev_signal and current_macd > current_signal:
            signals.append(StrategySignal(
                code=code,
                direction="long",
                strength=0.8,
                price=price,
                reason=f"MACD金叉: macd={current_macd:.4f}, signal={current_signal:.4f}",
            ))

        elif prev_macd >= prev_signal and current_macd < current_signal:
            signals.append(StrategySignal(
                code=code,
                direction="short",
                strength=0.8,
                price=price,
                reason=f"MACD死叉: macd={current_macd:.4f}, signal={current_signal:.4f}",
            ))

        return StrategyResult(signals=signals)

    def _ema(self, values: list, period: int) -> list:
        """Calculate EMA."""
        if len(values) < period:
            return values

        ema = [sum(values[:period]) / period]
        multiplier = 2 / (period + 1)

        for value in values[period:]:
            ema.append((value - ema[-1]) * multiplier + ema[-1])

        return ema


class RSIStrategy(BaseStrategy):
    """RSI momentum strategy."""

    def __init__(self, params: dict | None = None):
        default_params = {
            "period": 14,
            "oversold": 30,
            "overbought": 70,
        }
        if params:
            default_params.update(params)
        super().__init__("RSI", default_params)

    def analyze(self, data: dict[str, Any]) -> StrategyResult:
        """Generate signals based on RSI."""
        close = data.get("close", [])
        if len(close) < self.params["period"] + 1:
            return StrategyResult(errors=["Insufficient data for RSI"])

        rsi = self._calculate_rsi(close, self.params["period"])
        current_rsi = rsi[-1]

        code = data.get("code", "")
        price = data.get("current_price", close[-1] if close else 0)
        signals = []

        if current_rsi < self.params["oversold"]:
            signals.append(StrategySignal(
                code=code,
                direction="long",
                strength=1 - (current_rsi / self.params["oversold"]),
                price=price,
                reason=f"RSI超卖: {current_rsi:.1f}",
            ))
        elif current_rsi > self.params["overbought"]:
            signals.append(StrategySignal(
                code=code,
                direction="short",
                strength=(current_rsi - self.params["overbought"]) / (100 - self.params["overbought"]),
                price=price,
                reason=f"RSI超买: {current_rsi:.1f}",
            ))

        return StrategyResult(signals=signals)

    def _calculate_rsi(self, values: list, period: int) -> list:
        """Calculate RSI."""
        deltas = [values[i] - values[i-1] for i in range(1, len(values))]
        gains = [d if d > 0 else 0 for d in deltas]
        losses = [-d if d < 0 else 0 for d in deltas]

        avg_gain = sum(gains[:period]) / period
        avg_loss = sum(losses[:period]) / period

        rsi = [50.0]
        for i in range(period, len(deltas)):
            avg_gain = (avg_gain * (period - 1) + gains[i]) / period
            avg_loss = (avg_loss * (period - 1) + losses[i]) / period

            if avg_loss == 0:
                rsi.append(100)
            else:
                rs = avg_gain / avg_loss
                rsi.append(100 - (100 / (1 + rs)))

        return rsi


class BreakoutStrategy(BaseStrategy):
    """Price breakout strategy."""

    def __init__(self, params: dict | None = None):
        default_params = {
            "lookback_period": 20,
            "volume_multiplier": 1.5,
        }
        if params:
            default_params.update(params)
        super().__init__("Breakout", default_params)

    def analyze(self, data: dict[str, Any]) -> StrategyResult:
        """Generate signals based on price breakout."""
        close = data.get("close", [])
        volume = data.get("volume", [])

        if len(close) < self.params["lookback_period"]:
            return StrategyResult(errors=["Insufficient data for breakout"])

        lookback = close[-self.params["lookback_period"]:]
        high = max(lookback[:-1]) if len(lookback) > 1 else lookback[0]
        current_price = close[-1]

        code = data.get("code", "")
        signals = []

        if current_price > high:
            avg_volume = sum(volume[-self.params["lookback_period"]:]) / self.params["lookback_period"]
            current_volume = volume[-1] if volume else 0

            strength = min(1.0, current_volume / (avg_volume * self.params["volume_multiplier"]))

            if strength > 0.5:
                signals.append(StrategySignal(
                    code=code,
                    direction="long",
                    strength=strength,
                    price=current_price,
                    target_price=current_price * 1.05,
                    reason=f"价格突破: {current_price:.2f} > {high:.2f}",
                ))

        return StrategyResult(signals=signals)


class CompositeStrategy(BaseStrategy):
    """Composite strategy combining multiple strategies."""

    def __init__(self, strategies: list[BaseStrategy], params: dict | None = None):
        super().__init__("Composite", params or {})
        self.strategies = strategies

    def analyze(self, data: dict[str, Any]) -> StrategyResult:
        """Combine signals from multiple strategies."""
        all_signals = []

        for strategy in self.strategies:
            if not strategy.enabled:
                continue

            result = strategy.analyze(data)
            all_signals.extend(result.signals)

        return StrategyResult(signals=all_signals)


class StrategyRegistry:
    """Registry for managing strategies."""

    _strategies: dict[str, type[BaseStrategy]] = {}

    @classmethod
    def register(cls, name: str, strategy_class: type[BaseStrategy]):
        """Register a strategy class."""
        cls._strategies[name] = strategy_class
        logger.info(f"Registered strategy: {name}")

    @classmethod
    def get(cls, name: str, params: dict | None = None) -> BaseStrategy:
        """Get a strategy instance by name."""
        if name not in cls._strategies:
            raise ValueError(f"Strategy '{name}' not registered")

        return cls._strategies[name](params)

    @classmethod
    def list_strategies(cls) -> list[str]:
        """List all registered strategies."""
        return list(cls._strategies.keys())


StrategyRegistry.register("MACD", MACDStrategy)
StrategyRegistry.register("RSI", RSIStrategy)
StrategyRegistry.register("Breakout", BreakoutStrategy)


__all__ = [
    "BaseStrategy",
    "MACDStrategy",
    "RSIStrategy",
    "BreakoutStrategy",
    "CompositeStrategy",
    "StrategySignal",
    "StrategyResult",
    "StrategyRegistry",
]
