from __future__ import annotations

"""Streaming React Loop - Token-level streaming for LangGraph.

This module implements from midify_plan13.md optimization:
- StreamingReactLoop: LLM streaming with token-by-token output
- AsyncGenerator: Yield tokens as they're generated
- Backpressure handling: Manage streaming with tool calls

Usage:
    async for chunk in streaming_react_with_tools(llm, tools, system, user):
        print(chunk, end="")
"""


from collections.abc import AsyncGenerator
from typing import Any

import orjson as json
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.outputs import ChatGenerationChunk
from langchain_core.tools import BaseTool

from app.core.logger import get_logger

from .react_loop import tool_result_payload

logger = get_logger(__name__)


async def streaming_react_with_tools(
    llm: BaseChatModel,
    tools: list[BaseTool],
    *,
    system: str,
    user: str,
    max_rounds: int = 8,
) -> AsyncGenerator[str, None]:
    """ReAct loop with streaming token output.

    Yields chunks as they're generated by the LLM.
    Handles tool calls between streaming chunks.
    """
    if not tools:
        async for chunk in llm.astream([SystemMessage(content=system), HumanMessage(content=user)]):
            if chunk.content:
                yield chunk.content
        return

    bound = llm.bind_tools(tools)
    messages: list[BaseMessage] = [SystemMessage(content=system), HumanMessage(content=user)]
    name_to_tool = {t.name: t for t in tools}

    for _round_idx in range(max_rounds):
        is_first_chunk = True

        async for chunk in bound.astream(messages):
            if isinstance(chunk, ChatGenerationChunk):
                content = chunk.message.content if chunk.message else ""
                if content:
                    yield content

                    if is_first_chunk:
                        is_first_chunk = False

        messages.append(AIMessage(content=""))

        ai_msg = messages[-1]
        if not isinstance(ai_msg, AIMessage) or not getattr(ai_msg, "tool_calls", None):
            return

        for call in getattr(ai_msg, "tool_calls", []):
            name = call.get("name") or ""
            tid = call.get("id") or ""
            raw_args = call.get("args") or {}
            tool = name_to_tool.get(name)

            yield f"\n[Calling tool: {name}]\n"

            if tool is None:
                payload = json.dumps({"ok": False, "error": f"unknown_tool:{name}"}, ensure_ascii=False)
            else:
                try:
                    out = await tool.ainvoke(raw_args) if hasattr(tool, "ainvoke") else tool.invoke(raw_args)
                    payload = tool_result_payload(out)
                except Exception as exc:
                    payload = json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False)

            tool_msg = ToolMessage(content=payload, tool_call_id=tid)
            messages.append(tool_msg)

            yield "[Tool result received]\n"


class StreamingReactNode:
    """LangGraph node that supports streaming output.

    Use this node in graph.py for token-level streaming.
    """

    def __init__(self, llm: BaseChatModel):
        self._llm = llm

    async def execute(
        self,
        state: dict[str, Any],
        tools: list[BaseTool],
        system_prompt: str,
        user_template: str,
        max_rounds: int = 8,
    ) -> AsyncGenerator[dict[str, Any], None]:
        """Execute with streaming output."""
        ticker = state.get("ticker", "")
        query = state.get("query", "")

        user = user_template.format(ticker=ticker, query=query)

        accumulated_content = ""

        async for chunk in streaming_react_with_tools(
            self._llm,
            tools,
            system=system_prompt,
            user=user,
            max_rounds=max_rounds,
        ):
            accumulated_content += chunk

            yield {
                "streaming_content": chunk,
                "accumulated_content": accumulated_content,
            }

        yield {
            "final_content": accumulated_content,
        }


def create_streaming_node(llm: BaseChatModel) -> StreamingReactNode:
    """Factory to create streaming react node."""
    return StreamingReactNode(llm)
