import pathlib

p = pathlib.Path("app/presentation/api/routes_v1_panorama.py")
lines = []
lines.append('"""Phase 8.3 Quant-Panorama God-View: full-trace aggregation API."""')
lines.append("from __future__ import annotations")
lines.append("from datetime import datetime, timezone")
lines.append("from typing import Any")
lines.append("from flask import Blueprint, request")
lines.append("from flask_login import login_required")
lines.append("from ...core.middleware.request_context import require_authenticated_user_id")
lines.append("from ...core.registry import register_routes")
lines.append("from ..api.common import ok_response, require_ctx_service")
lines.append("from ..api.v1_context import ApiV1Context")
lines.append("")
lines.append("DEFAULT_LIMIT = 50")
lines.append("")
lines.append("def _uid() -> int:")
lines.append("    return require_authenticated_user_id()")
lines.append("")
lines.append("@register_routes(name=\"panorama\", context=\"system\", description=\"Quant-Panorama God-View\")")
lines.append("def register_panorama_routes(blueprint: Blueprint, ctx: ApiV1Context) -> None:")
lines.append("    \"\"\"Register panorama aggregation routes.\"\"\"")
lines.append("    legacy = ctx.enable_legacy_response_fields")
lines.append("")
lines.append("    @blueprint.get(\"/panorama/full-trace\")")
lines.append("    @login_required")
lines.append("    def panorama_full_trace() -> Any:")
lines.append("        \"\"\"Aggregate cross-module DecisionContext traces.\"\"\"")
lines.append("        user_id = _uid()")
lines.append("        symbol = (request.args.get(\"symbol\") or \"\").strip()")
lines.append("        limit_str = (request.args.get(\"limit\") or str(DEFAULT_LIMIT)).strip()")
lines.append("        try:")
lines.append("            limit = max(1, min(200, int(limit_str)))")
lines.append("        except (ValueError, TypeError):")
lines.append("            limit = DEFAULT_LIMIT")
lines.append("")
lines.append("        uid = f\"panorama-{__import__('uuid').uuid4().hex[:12]}\"")
lines.append("        now = datetime.now(timezone.utc).isoformat()")
lines.append("        panorama: dict[str, Any] = {")
lines.append('            "panorama_id": uid,')
lines.append('            "generated_at": now,')
lines.append('            "subject": f"user:{user_id}",')
lines.append("        }")
lines.append("")
lines.append("        # 1. Arbiter verdicts")
lines.append('        meta = require_ctx_service(ctx, "meta_arbiter_service", required=False)')
lines.append("        if meta and symbol:")
lines.append("            try:")
lines.append('                panorama["arbiter_verdicts"] = meta.synthesize(symbol)')
lines.append("            except Exception as e:")
lines.append('                panorama["arbiter_verdicts"] = {"error": str(e)}')
lines.append("")
lines.append("        # 2. Evolution status")
lines.append('        evo = require_ctx_service(ctx, "evolution_arbiter_service", required=False)')
lines.append("        if evo:")
lines.append("            try:")
lines.append('                panorama["evolution_status"] = evo.get_status()')
lines.append("            except Exception as e:")
lines.append('                panorama["evolution_status"] = {"error": str(e)}')
lines.append("")
lines.append("        # 3. Data truth alerts")
lines.append('        guardian = require_ctx_service(ctx, "data_truth_guardian_service", required=False)')
lines.append("        if guardian:")
lines.append("            try:")
lines.append('                panorama["data_truth_alerts"] = guardian.get_manifest()')
lines.append("            except Exception as e:")
lines.append('                panorama["data_truth_alerts"] = {"error": str(e)}')
lines.append("")
lines.append("        # 4. Module health")
lines.append("        from app.core.registry import check_all_modules_health")
lines.append("        try:")
lines.append('            panorama["module_health"] = check_all_modules_health()')
lines.append("        except Exception as e:")
lines.append('            panorama["module_health"] = {"error": str(e)}')
lines.append("")
lines.append('        panorama["reasoning_trace"] = [f"Panorama for user:{user_id}", f"symbol={symbol or chr(97)+chr(108)+chr(108)}"]')
lines.append("")
lines.append("        return ok_response(data=panorama, legacy_alias_key=None, enable_legacy_alias=legacy)")
lines.append("")

p.write_text("\n".join(lines), encoding="utf-8")
print("Created panorama route")
