"""Application Data Transfer Objects (DTOs)."""

from .investment_manager_dto import (
    InvestmentManagerDTO,
    LeaderboardItemDTO,
    ManagerProfileDTO,
)
from .manager_dto import (
    LeaderboardQueryDTO,
    ManagerDeployDTO,
    ManagerProfileUpdateDTO,
)
from .market_data_dto import (
    BacktestCompareRequestDTO,
    BacktestRequestDTO,
    FinancialStashDTO,
    LonghuEntry,
    MarketOverviewDTO,
    MarketSentimentDTO,
    MarketSentimentMetricsDTO,
    NewsSnapshotDTO,
    SelectionRequestDTO,
    StockDetailDTO,
    StockHistoryDTO,
    StockMovementDTO,
    StockQuoteDTO,
    YanbaoEntry,
)
from .portfolio_dto import (
    AttributionResultDTO,
    OptimizationRequestDTO,
    OptimizationResultDTO,
    PortfolioPositionDTO,
    PortfolioSnapshotDTO,
    RebalanceAlertDTO,
    RiskBudgetDTO,
)
from .scanner_dto import ScannerSnapshotDTO, ScannerStatusDTO, ScanResultDTO
from .signal_dto import (
    SignalFlagBackfillDTO,
    SignalFlagQueryDTO,
    SignalFlagUpdateDTO,
)
from .user_dto import (
    ChangePasswordCommand,
    CreateUserCommand,
    RoleDTO,
    UserAccountDTO,
    UserCreateDTO,
    UserDTO,
    UserUpdateDTO,
)
from .watchlist_dto import (
    WatchlistAddStockDTO,
    WatchlistAddSymbolDTO,
    WatchlistCreateDTO,
    WatchlistRemoveStockDTO,
    WatchlistUpdateDTO,
)

__all__ = [
    "BacktestCompareRequestDTO",
    "BacktestRequestDTO",
    "SelectionRequestDTO",
    "LonghuEntry",
    "YanbaoEntry",
    "FinancialStashDTO",
    "MarketSentimentDTO",
    "MarketOverviewDTO",
    "StockQuoteDTO",
    "StockDetailDTO",
    "NewsSnapshotDTO",
    "StockHistoryDTO",
    "MarketSentimentMetricsDTO",
    "StockMovementDTO",
    "UserDTO",
    "UserAccountDTO",
    "UserCreateDTO",
    "UserUpdateDTO",
    "RoleDTO",
    "CreateUserCommand",
    "ChangePasswordCommand",
    "InvestmentManagerDTO",
    "ManagerProfileDTO",
    "LeaderboardItemDTO",
    "ScannerSnapshotDTO",
    "ScannerStatusDTO",
    "ScanResultDTO",
    "WatchlistAddSymbolDTO",
    "WatchlistCreateDTO",
    "WatchlistUpdateDTO",
    "WatchlistAddStockDTO",
    "WatchlistRemoveStockDTO",
    "PortfolioPositionDTO",
    "PortfolioSnapshotDTO",
    "OptimizationRequestDTO",
    "OptimizationResultDTO",
    "RebalanceAlertDTO",
    "AttributionResultDTO",
    "RiskBudgetDTO",
    "SignalFlagQueryDTO",
    "SignalFlagBackfillDTO",
    "SignalFlagUpdateDTO",
    "LeaderboardQueryDTO",
    "ManagerProfileUpdateDTO",
    "ManagerDeployDTO",
]
