apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  namespace: quant-atlas
spec:
  selector:
    app: mysql
    role: master
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
