from __future__ import annotations

"""Factor Vault - persistent storage for discovered alpha factors.

This implements "Factor Vault" from the roadmap:
- Persist every alpha expression generated by rd-agent
- Tag with regime labels (trending, ranging, volatile, etc)
- Enable knowledge-guided factor search
"""


from abc import ABC, abstractmethod
from datetime import datetime
from enum import Enum
from typing import Any


class MarketRegime(Enum):
    """Market regime labels for factor categorization."""

    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    RANGING = "ranging"
    VOLATILE = "volatile"
    LOW_VOLATILITY = "low_volatility"
    HIGH_VOLUME = "high_volume"
    LOW_VOLUME = "low_volume"


class FactorVaultStorage(ABC):
    """Port for storing alpha factor expressions."""

    @abstractmethod
    def save_factor(
        self,
        formula: str,
        *,
        regime: str | None = None,
        sharpe_ratio: float | None = None,
        max_drawdown: float | None = None,
        backtest_result: dict[str, Any] | None = None,
        metadata: dict[str, Any] | None = None,
        parents: list[str] | None = None,
    ) -> str:
        """Save a factor expression.

        Args:
            formula: Alpha expression
            regime: Market regime (trending_up, ranging, etc)
            sharpe_ratio: Backtest Sharpe ratio
            max_drawdown: Backtest max drawdown
            backtest_result: Full backtest result
            metadata: Additional metadata
            parents: List of parent factor IDs

        Returns:
            factor_id
        """
        raise NotImplementedError

    @abstractmethod
    def get_factor(self, factor_id: str) -> dict[str, Any] | None:
        """Get factor by ID."""
        raise NotImplementedError

    @abstractmethod
    def search_factors(
        self,
        *,
        regime: str | None = None,
        min_sharpe: float | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        """Search factors by criteria."""
        raise NotImplementedError

    @abstractmethod
    def list_recent_factors(self, limit: int = 50) -> list[dict[str, Any]]:
        """List recent factors."""
        raise NotImplementedError

    def patch_factor(self, factor_id: str, **updates: Any) -> bool:
        """Merge ``updates`` into an existing factor record (optional port extension)."""
        _ = factor_id, updates
        return False


class InMemoryFactorVaultStorage(FactorVaultStorage):
    """In-memory implementation of FactorVault for development."""

    def __init__(self) -> None:
        self._factors: dict[str, dict[str, Any]] = {}
        self._counter = 0

    def save_factor(
        self,
        formula: str,
        *,
        regime: str | None = None,
        sharpe_ratio: float | None = None,
        max_drawdown: float | None = None,
        backtest_result: dict[str, Any] | None = None,
        metadata: dict[str, Any] | None = None,
        parents: list[str] | None = None,
    ) -> str:
        self._counter += 1
        factor_id = f"factor_{self._counter:06d}"
        self._factors[factor_id] = {
            "factor_id": factor_id,
            "formula": formula,
            "regime": regime,
            "sharpe_ratio": sharpe_ratio,
            "max_drawdown": max_drawdown,
            "backtest_result": backtest_result or {},
            "metadata": metadata or {},
            "parents": parents or [],
            "created_at": datetime.utcnow().isoformat(),
        }
        return factor_id

    def get_factor(self, factor_id: str) -> dict[str, Any] | None:
        return self._factors.get(factor_id)

    def search_factors(
        self,
        *,
        regime: str | None = None,
        min_sharpe: float | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        results = list(self._factors.values())
        if regime:
            results = [f for f in results if f.get("regime") == regime]
        if min_sharpe is not None:
            results = [f for f in results if (f.get("sharpe_ratio") or 0) >= min_sharpe]
        results.sort(key=lambda x: x.get("created_at", ""), reverse=True)
        return results[:limit]

    def list_recent_factors(self, limit: int = 50) -> list[dict[str, Any]]:
        factors = list(self._factors.values())
        factors.sort(key=lambda x: x.get("created_at", ""), reverse=True)
        return factors[:limit]

    def patch_factor(self, factor_id: str, **updates: Any) -> bool:
        rec = self._factors.get(factor_id)
        if not rec:
            return False
        meta_patch = updates.pop("metadata", None)
        if isinstance(meta_patch, dict):
            rec["metadata"] = {**(rec.get("metadata") or {}), **meta_patch}
        bt_patch = updates.pop("backtest_result", None)
        if isinstance(bt_patch, dict):
            rec["backtest_result"] = {**(rec.get("backtest_result") or {}), **bt_patch}
        rec.update(updates)
        return True


_global_factor_vault: FactorVaultStorage | None = None


def get_factor_vault() -> FactorVaultStorage:
    """Get global FactorVault instance."""
    global _global_factor_vault
    if _global_factor_vault is None:
        _global_factor_vault = InMemoryFactorVaultStorage()
    return _global_factor_vault


def set_factor_vault(vault: FactorVaultStorage) -> None:
    """Set global FactorVault instance."""
    global _global_factor_vault
    _global_factor_vault = vault
